
# ASP.NET Core
# Build and test ASP.NET Core projects targetting .Net Core
# Add steps that run tests, creare a Nuget package, deploy and more

trigger:
- main

pool: 
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'